name: CI

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn lint

  build:
    name: Build
    env:
      NEXT_PUBLIC_API_KEY: '${{ secrets.NEXT_PUBLIC_API_KEY }}'
      NEXT_PUBLIC_AUTH_DOMAIN: '${{ secrets.NEXT_PUBLIC_AUTH_DOMAIN }}'
      NEXT_PUBLIC_PROJECT_ID: '${{ secrets.NEXT_PUBLIC_PROJECT_ID }}'
      NEXT_PUBLIC_STORAGE_BUCKET: '${{ secrets.NEXT_PUBLIC_STORAGE_BUCKET }}'
      NEXT_PUBLIC_MESSAGIN_SENDER_ID: '${{ secrets.NEXT_PUBLIC_MESSAGIN_SENDER_ID }}'
      NEXT_PUBLIC_APP_ID: '${{ secrets.NEXT_PUBLIC_APP_ID }}'
      NEXT_PUBLIC_MEASUREMENT_ID: '${{ secrets.NEXT_PUBLIC_MEASUREMENT_ID }}'
      NEXT_PUBLIC_ADMIN_UID_1: '${{ secrets.NEXT_PUBLIC_ADMIN_UID_1 }}'
      NEXT_PUBLIC_ADMIN_UID_2: '${{ secrets.NEXT_PUBLIC_ADMIN_UID_2 }}'
      NEXT_PUBLIC_ADMIN_UID_3: '${{ secrets.NEXT_PUBLIC_ADMIN_UID_3 }}'
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      - run: CI='false' yarn build
